services:
  test_db:
    image: postgres:15-alpine # Стабильная
    container_name: test_db
    ports:
      - "5444:5432" #  Проброс порта для доступа к PostgreSQL
    environment:
      POSTGRES_USER: postgres #  Логин для PostgreSQL
      POSTGRES_PASSWORD: password #  Пароль для PostgreSQL
      POSTGRES_DB: postgres #  Имя базы данных
    volumes:
      - test_db:/var/lib/postgresql/data #  Том для хранения данных БД
    networks:
      - test_db_network #  Присоединяем контейнер к сети

  pgadmin_container:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: example@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CSRF_PROTECTION: "False"
      PGADMIN_CONFIG_REMOTE_USER_ENABLED: "True"
    ports:
      - "5050:80"
    networks:
      - test_db_network


volumes:
  test_db: #  Определение тома для хранения данных PostgreSQL

networks:
  test_db_network: #  Определение сети для контейнеров
    driver: bridge #  Использование мостовой сети (по умолчанию)
